### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by idgas01** [Stateford/Display-Lock#110]
I am going to close this ticket as soon as I create it, but I just wanted to take a moment to thank the developers of this program.  I have had this game called Ghostbusters: The Video Game Remastered for 2-3 years now.  When I played it, the cursor would always leave the window.  I prefer windowed mode with borders, but that game forced me to play in borderless fullscreen or fullscreen.  I forgot.  I did try to find a mouse cursor lock program back then, but it didn't work.  So fast forward to today, I tried a popular mouse lock program and it didn't work with the game.  Found another program, but it was a trial that lasted like two minutes and then they wanted me to pay for a monthly subscription.  Tried a third program, and my game window wasn't even listed in the windows list.  Finally tried your version, and it worked perfectly.  Thank you so much!  I can't wait to use it on Ghostbusters and some other games that have the same problem.

**Comment by Stateford** [comment]
Thank you for creating this issue. It's not often these small projects get any recognition. If you run into any issues feel free to open a ticket.

**Comment by idgas01** [comment]
I think your program would be more popular if it was easy to find when doing a search on Google.  I had tried many times searching for things like "cursor lock window" and your program didn't come up.  It wasn't till I accidentally searched for "cursor lock github" that I found your Github.  But most people wouldn't search for "github", so it was pure luck.  On a side note, I'm not sure why you have a hyphen in the program name.  I thought it would look better as "Display Lock" instead of "Display-Lock".  I ended up renaming it myself.  The "Display Lock" is a unique name, so it's good enough I guess.  But it isn't every descriptive.  It doesn't say anything about cursors.  And what about locking the cursor in a window?  It doesn't just lock cursors to screens.  I realize that just about any name you can think of has already been taken.  That's why "Display Lock" without the hyphen is okay.  And if I were to "improve" it, I would probably pick a name that is too long and descriptive.  Like "Cursor Lock for Windows and Displays".  Wow, that's really long.  Or maybe a brand name thing.  "Stateford Cursor Lock".  That would differentiate it from an existing program called "Cursor Lock" because of the "Stateford" but it would be really easy to find when doing a search on Google.  I was surprised that your program was just one tiny exe with no dlls, files, or subfolders.  It's a bit weird because I have a Programs folder that I created on my C drive, and all the programs are in folders.  But yours isn't.  It's just an exe.  But that's cool.  And I can always put it in a folder, LOL.  Why didn't I think abou that?  It's actually extremely impressive how compact it is, and how it is just one file exe and not a folder with dlls and subfolders.  I was kinda wondering why there wasn't a "Start with Windows" option, but I decided it's not something that I need or want.  One, I can just create a shortcut and drag it into the Startup folder.  And two, I don't even want it to start with Windows or run 24/7, as I rarely ever play those troublesome games.  But it wouldn't hurt to add the feature, I guess.  I only tested your program for like five seconds to see if it would work with the Ghostbusters video game remake, and it did.  It seems like the best mouse cursor program in existence and I'm truly happy and grateful to have it.  I hope other people find it too.

**Comment by Stateford** [comment]
Thanks. It's kind of hard to change the name now, and it's hard to add more tags to make it more searchable.

It's a small EXE because I wanted it to take the least resources possible, while being fully functional.

Making an installer isn't exactly the easiest thing, especially for windows due to all the registry edits that have to happen. I could probably make an installer for it in the future, but I don't really see many people using the program to warrant the effort.

I also didn't add a startup with windows option because it requires editing the registry. It's probably easy to add, since there's no hard install location and the application can be moved around, it's not really possible to add it. If an installer is created it's trivial to add this.

**Comment by idgas01** [comment]
Oh okay.  That makes sense.  Just keep everything the same then.  I'm glad that I found your program.  I hope that I never accidentally lose it.  I'm glad that it doesn't use registry keys.  It makes things simpler and better.
