### ISSUE TITLE
Create new dialog for creating hotkeys

### ISSUE THREAD

**Issue by Stateford** [Stateford/Display-Lock#72]
A new dialog should appear when changing hotkeys.

New hotkeys should be enabled, such as toggling borderless windowed and full screen modes

- [ ] Dialog Box

The code for all of this is within the project

**Comment by linton-dawson** [comment]
Hello @idietmoran ! I'd like to work on this issue. Is it fine if I post my doubts here ?

**Comment by idietmoran** [comment]
Yes, I'm always open to suggestions.

**Comment by idietmoran** [comment]
Issue now relies on #42 to be completed.

The dialog can still be created/designed, but it cannot be fully functional at the moment.
